float64 Car_Roll_rad
float64 Car_Pitch_rad
float64 Car_Yaw_rad
float64 Car_vx_mps
float64 Car_vy_mps
float64 Car_vz_mps
float64 Car_RollVel_rps
float64 Car_PitchVel_rps
float64 Car_YawVel_rps
float64 Car_ax_mpss
float64 Car_ay_mpss
float64 Car_az_mpss
float64 Car_RollAcc_rpss
float64 Car_PitchAcc_rpss
float64 Car_YawAcc_rpss

float64 Steer_WhlAng_rad
float64 VC_Gas
float64 VC_Brake
float64 VC_SelectorCtrl

float64 x_lin_vel_no_gravity_mps    # m/s ( current_vehicle_velocity )
float64 y_lin_vel_no_gravity_mps    # m/s
float64 z_lin_vel_no_gravity_mps    # m/s
float64 x_lin_vel_with_gravity_mps  # m/s
float64 y_lin_vel_with_gravity_mps  # m/s
float64 z_lin_vel_with_gravity_mps  # m/s

float64 x_lin_acc_no_gravity_mpss    # m/s2
float64 y_lin_acc_no_gravity_mpss    # m/s2
float64 z_lin_acc_no_gravity_mpss    # m/s2
float64 x_lin_acc_with_gravity_mpss  # m/s2
float64 y_lin_acc_with_gravity_mpss  # m/s2
float64 z_lin_acc_with_gravity_mpss  # m/s2

float64 x_rot_vel_no_gravity_rps    # rad/s
float64 y_rot_vel_no_gravity_rps    # rad/s
float64 z_rot_vel_no_gravity_rps    # rad/s ( yaw_rate )
float64 x_rot_vel_with_gravity_rps  # rad/s
float64 y_rot_vel_with_gravity_rps  # rad/s
float64 z_rot_vel_with_gravity_rps  # rad/s

float64 x_rot_acc_no_gravity_rps    # rad/s2
float64 y_rot_acc_no_gravity_rps    # rad/s2
float64 z_rot_acc_no_gravity_rps    # rad/s2
float64 x_rot_acc_with_gravity_rps  # rad/s2
float64 y_rot_acc_with_gravity_rps  # rad/s2
float64 z_rot_acc_with_gravity_rps  # rad/s2

